version: 0.2
environment_variables:
    plaintext:
        "S3_BUCKET": ""
phases:
    install:
        commands:
        - pwd
    pre_build:
        commands:
        - echo Pre Build started on `date`
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH="$PATH:`pwd`/flutter/bin"
        - flutter precache
        - flutter doctor
    build:
        commands:
            - flutter build web --release
            - aws s3 cp build/web s3://cryp-proline-frontend-985194350712-us-east-1 --recursive
            - aws cloudfront create-invalidation --distribution-id E25L7XZNT4YV5F --paths "/*"
    post_build:
        commands: